server:
  port: 10086

# SpringMVC 使用 JDBC 连接数据库，WebFlux 使用 R2DBC 连接数据库
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/douban?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    pool:
      enabled: true
      initial-size: 10
      max-size: 20
      max-idle-time: 10m
      max-acquire-time: 30s
      max-create-connection-time: 30s
      validation-query: select 1
